### ISSUE TITLE
[BUG] Potion display item does not display duration of potion.

### ISSUE THREAD

**Issue by mibby** [PotatoCraft-Studio/QuickShop-Reremake#266]
### Description

There currently does not seem to be any way to differentiate from potion types with different durations.

### Steps to reproduce

* Create a shop with potion of strength 3 minutes.
* Create a shop with potion of strength 8 minutes.
* No way to differentiate between the two sold.

### Expected Behaviour

Some way to check items being sold.

### Additional Context

While ``use-effect-for-potion-item: true`` helps a little bit by putting the potion effect type on the sign (if it fits), there is still no way to differentiate between items with different nbt. These are my proposed possible solutions that would work with potions and other items such as enchanted tools;

1) Allow players to open chests to inspect items or create a fake inventory so you can hover over the item inside a GUI container to get exact info what is being sold. If the former method, charge the player if the item is taken from the chest or cancel if cannot afford.

2) Allow players to ``/qs inspect`` or right click the floating item hologram / sign to output full info of an item in chat. Either hover tooltip or plain text of full details. Hover tooltip can be a hook with the ShowItem spigot plugin or similar native implementation?
![link](https://i.imgur.com/nCYoV5r.png)

3) Append a potion duration time and effect type (by color or full name) to the name of item in the hologram instead of just 'Potion'.

**Comment by sandtechnology** [comment]
For 1 and 2 you mentioned in Additional Context, it has been impl for a long time, just click the shop and let the mouse over the item name or click preview will do this.
For 3, In the most common case, there should have no vanilla potion being sold or it should have custom color and name for divide into different item, since vanilla client also show as you can see in floating item until you check the tooltip, it look like is the same item in your hotbar and inventory, so I think this feature could be no needed at this case.
