### ISSUE TITLE
[BUG] Caching sha2 authentication on MySQL 8.0 is not compatitable

### ISSUE THREAD

**Issue by TSStudio** [PotatoCraft-Studio/QuickShop-Reremake#273]
### Description

`Public Key Retrieval is not allowed` Error caused. 
With SSL disabled, allowPublicKeyRetrieval=true is required for caching sha2 authentication.

### Steps to reproduce

Create a MySQL user using MySQL8 and caching sha2 authentication.  And configurate in config file of QS with MySQL and without SSL. Open the server up.

### Expected Behaviour

It should use `allowPublicKeyRetrieval`

### Screenshots

No screenshot required for a bug when startup.

### `/qs paste` URL

https://paste.helpch.at/yifexuzuze.less

**Comment by sandtechnology** [comment]
`allowPublicKeyRetrieval` is unsafe for connection because it can be mitmed by attacker, so it need to enable explicitly, I have add `mysql-connect-options` settings in the snapshot to let user add it, you can test if that work: 
https://ci.codemc.io/job/PotatoCraft-Studio/job/QuickShop-Reremake-SNAPSHOT/2422/artifact/target/QuickShop-5.1.1.0-SNAPSHOT.jar
