### ISSUE TITLE
[BUG] lost connection: Chat message validation failure

### ISSUE THREAD

**Issue by Jernee** [PotatoCraft-Studio/QuickShop-Reremake#419]
### Description

When using the chat buttons occasionally the player gets kicked for Chat message validation failure.

### Steps to reproduce

1. Create quickshop.
2. Right click sign.
3. Use chat buttons like remove.
4. lost connection: Chat message validation failure

### Expected Behaviour

The buttons shouldn't get you disconnected.

### Screenshots

N/A

### `/qs paste` URL

https://paste.helpch.at/puvirumuvu

**Comment by sandtechnology** [comment]
does this happen to the other plugin message?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jernee ***@***.***>
Sent: Thursday, November 16, 2023 9:59:16 AM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [BUG] lost connection: Chat message validation failure (Issue #419)


Description

When using the chat buttons occasionally the player gets kicked for Chat message validation failure.

Steps to reproduce

  1.  Create quickshop.
  2.  Right click sign.
  3.  Use chat buttons like remove.
  4.  lost connection: Chat message validation failure

Expected Behaviour

The buttons shouldn't get you disconnected.

Screenshots

N/A

/qs paste URL

https://paste.helpch.at/puvirumuvu

Additional Context

No response
