### ISSUE TITLE
[BUG] FabledSkyblock integration

### ISSUE THREAD

**Issue by Sh3r1ffCZ** [PotatoCraft-Studio/QuickShop-Reremake#420]
### Description

Config:
  #FabledSkyblock Integration
  fabledskyblock:
    # If a player wants to create a shop, the player must have the quickshop-create flag.
    # If a player wants to trade a shop, the player must have the quickshop-trade flag.
    enable: true
    #Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area?
    whitelist-mode: false
    create:
    - MEMBER
    - OWNER
    - OPERATOR
    - COOP

Plugin: FabledSkyBlock-3.0.0-b6-SNAPSHOT.jar
Java: Java 20.0.1 Oracle
Server: 1.20.1 (pufferfish-paperclip-1.20.1-R0.1-SNAPSHOT-reobf)

### Steps to reproduce

Immediately upon powering up the server, an error pops up regarding integration.

https://paste.gg/p/anonymous/92c69153457d445ca031196bacb3efe4

### Expected Behaviour

I tried to change java and paper, but unfortunately without result.

### Screenshots

https://paste.gg/p/anonymous/92c69153457d445ca031196bacb3efe4

### `/qs paste` URL

https://paste.helpch.at/kufetumabo

**Comment by sandtechnology** [comment]
You are using snapshot, and it's a premium plugin, original support is a pr from their side, now its repo is not updating its api jar, so there is no way to get the newer plugin support, please contact them for updating its api jar  (skyblock jar for their repo : https://repo.craftaro.com/repository/public/)

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Sh3r1ffCZ ***@***.***>
Sent: Thursday, November 16, 2023 1:12:19 PM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [BUG] FabledSkyblock integration (Issue #420)


Description

Config:
#FabledSkyblock Integration
fabledskyblock:
# If a player wants to create a shop, the player must have the quickshop-create flag.
# If a player wants to trade a shop, the player must have the quickshop-trade flag.
enable: true
#Should we prevent the creation of a shop or trade with a shop outside FabledSkyblock's area?
whitelist-mode: false
create:
- MEMBER
- OWNER
- OPERATOR
- COOP

Plugin: FabledSkyBlock-3.0.0-b6-SNAPSHOT.jar
Java: Java 20.0.1 Oracle
Server: 1.20.1 (pufferfish-paperclip-1.20.1-R0.1-SNAPSHOT-reobf)

Steps to reproduce

Immediately upon powering up the server, an error pops up regarding integration.

https://paste.gg/p/anonymous/92c69153457d445ca031196bacb3efe4

Expected Behaviour

I tried to change java and paper, but unfortunately without result.

Screenshots

https://paste.gg/p/anonymous/92c69153457d445ca031196bacb3efe4

/qs paste URL

https://paste.helpch.at/kufetumabo

Additional Context

No response
