### ISSUE TITLE
[BUG] Offline players don't get paid, the money disappears.

### ISSUE THREAD

**Issue by justLxy** [PotatoCraft-Studio/QuickShop-Reremake#421]
### Description

The store owner doesn't get the money if he's not online, but the money is still deducted as usual from the person who buys it, and the person who sells it doesn't get it, and the money disappears.

### Steps to reproduce

Any player buys an item from a shopkeeper who is now offline. 

### Expected Behaviour

Offline store owners will get money when they come online.

### Screenshots

none

### `/qs paste` URL

https://paste.helpch.at/vunogofugu

**Comment by sandtechnology** [comment]
Are you using eco sync plugin? if so, it should be its issue, quickshop will ensure the money was transfer successfully, otherwise it will rollback and report the error

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: 花桥荣记 ***@***.***>
Sent: Sunday, November 26, 2023 1:22:31 PM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [BUG] Offline players don't get paid, the money disappears. (Issue #421)


Description

The store owner doesn't get the money if he's not online, but the money is still deducted as usual from the person who buys it, and the person who sells it doesn't get it, and the money disappears.

Steps to reproduce

Any player buys an item from a shopkeeper who is now offline.

Expected Behaviour

Offline store owners will get money when they come online.

Screenshots

none

/qs paste URL

https://paste.helpch.at/vunogofugu

Additional Context

No response

―
