### ISSUE TITLE
[BUG] Could not pass event InventoryCloseEvent to QuickShop v5.1.2.5

### ISSUE THREAD

**Issue by MySoulcutting** [PotatoCraft-Studio/QuickShop-Reremake#424]
### Description

Players closure Inventory and occasionally appear
Use Catserver 1.16.5

### Steps to reproduce

CloseEvent

### Expected Behaviour

No errors

### Screenshots

![1e12dbff54f1f9726d6442a2abaf841e](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/72398605/b0016bce-b190-41af-b718-32e1396efefe)

### `/qs paste` URL

https://paste.helpch.at/ejevikolid.rb

**Comment by sandtechnology** [comment]
It's catserver side issue, please report to them

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: White_Souls ***@***.***>
Sent: Friday, December 1, 2023 9:43:46 AM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [BUG] Could not pass event InventoryCloseEvent to QuickShop v5.1.2.5 (Issue #424)


Description

Players closure Inventory and occasionally appear
Use Catserver 1.16.5

Steps to reproduce

CloseEvent

Expected Behaviour

No errors

Screenshots

1e12dbff54f1f9726d6442a2abaf841e.png (view on web)<https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/72398605/b0016bce-b190-41af-b718-32e1396efefe>

/qs paste URL

https://paste.helpch.at/ejevikolid.rb

Additional Context

No response
