### ISSUE TITLE
[PERFORMANCE] Plugin Creating A Lot of Threads

### ISSUE THREAD

**Issue by Kyrobi** [PotatoCraft-Studio/QuickShop-Reremake#430]
### Description

The plugin is creating a lot of database connection threads.

### Steps to reproduce

I'm not sure how it's reproduced. I was checking my spark report since the server was lagging a little bit.

### Expected Behaviour

Quickshop to not create so many connection threads

### Screenshots

![image](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/20980266/5d7af01d-6fb2-4119-9264-a4a0ba4b9d55)

### `/qs paste` URL

https://paste.helpch.at/efemozical

### Spark Sample URL

https://spark.lucko.me/bBG8Lh2qDN

**Comment by sandtechnology** [comment]
spark report is unable to load, please check that

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kyrobi ***@***.***>
Sent: Monday, December 25, 2023 4:25:21 AM
To: PotatoCraft-Studio/QuickShop-Reremake ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PotatoCraft-Studio/QuickShop-Reremake] [PERFORMANCE] Plugin Creating A Lot of Threads (Issue #430)


Description

The plugin is creating a lot of database connection threads.

Steps to reproduce

I'm not sure how it's reproduced. I was checking my spark report since the server was lagging a little bit.

Expected Behaviour

Quickshop to not create so many connection threads

Screenshots

image.png (view on web)<https://github.com/PotatoCraft-Studio/QuickShop-Reremake/assets/20980266/5d7af01d-6fb2-4119-9264-a4a0ba4b9d55>

/qs paste URL

https://paste.helpch.at/efemozical

Spark Sample URL

https://spark.lucko.me/bBG8Lh2qDN

Additional Context

No response

**Comment by Kyrobi** [comment]
Oops. Here's another one: https://spark.lucko.me/kU2cw21l8B

**Comment by sandtechnology** [comment]
> Oops. Here's another one: https://spark.lucko.me/kU2cw21l8B

Sorry for late reply, but spark report is expired again, could you send a new report there?

**Comment by Kyrobi** [comment]
I've switched QS to using a different database and it's not happening again so I won't be able to generate another spark report
