### ISSUE TITLE
[solved] Display "you can buy 0 when it should be the amouth we can 

### ISSUE THREAD

**Issue by dryter97** [PotatoCraft-Studio/QuickShop-Reremake#52]
### Description

hello there so... i got this weird thing in chat when user want to buy on a shot

any solution?
running 5.0.0.17 from 3 december
occure also on 5.0.0.16 reason why we jumped on dev build.
still persist on 5.1.0.2

this message im talking about is the line 112 in message.json
at the buttom you can see "enter in chat, how many you wish to BUY. you can buy 0 Enter all to buy them all.

wich is 0 the issus i actually got 4 empty slot and 4*64 = 256 i can buy
its not doing it only for the iron and its also doing it for player limited amount shop too.

OLD REPORT NOT TAKED SERIOUSLY....
https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/17

thanks to take your time fellow humain. My life isnt minecraft...

### Steps to reproduce

1.create a chest.

2.put some item in it to sell it from quickshop.

3.tap on it to by some

4.read the chat

### Expected Behaviour

not showing 0 but the amounth you are suposed to be able to buy

### Screenshots

![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3437313838323831323237303730363731392f3931373235373932313438343730313733362f756e6b6e6f776e2e706e67](https://user-images.githubusercontent.com/16638986/147714960-5cb980a3-5c15-4871-bd35-a6d2b972020d.png)

### `/qs paste` URL

https://paste.helpch.at/vubakukotu

### Additional Context

https://github.com/PotatoCraft-Studio/QuickShop-Reremake/issues/17

**Comment by sandtechnology** [comment]
First of all, a rely and apologize for the previous issue, you can reopen the issue if you still having the same issue, and github will auto close a issue if a commit include "Fix #[issue number]",may be I should just give a issue a number and give a "working-on" label, that is my fault, sorry for that, and this issue was fixed for twice times, I also reproduce and test it to confirm it was fixed in the 5.1.0.0.

For this issue, there have three possibly:
1. The item inside does not match the trading item (Item matcher may going wrong)
2. The owner does not have enough memory to afford this
3. The code logic having bug inside

For the first solution, in that time there have couple bugs was fixed, so I want to test if the latest snapshot fix it.
For the second solution, I think it may be is the Item matcher issue, so I suggest to use bukkit one.
For the third solution, there have a bug related to display message was fixed, so I want to test if this was related.
And after that you give a picture to me, in that day I figure out that have a logic bug there and fixed it, I also working on coloring bug, configuration comment in this time, so I push the commits in the next day and ask if this bug fixed for you, and you reply will test it, then after 17 days you rely it was not fixed.

So come back for this new issue, please provide the latest paste url, also provide the item nbt information by vanilla command `/data get block <x> <y> <z>`, just provide the shop chest information is okay.

**Comment by dryter97** [comment]
So i tested on a old version i currently miss time to test it back. Im answering from my jobs.

It was working for some item. But some other item wasnt. Ill try to get time to test it out correctly.

**Comment by dryter97** [comment]
Trust me about the money its not an issue

**Comment by dryter97** [comment]
just gonna close it i test it correcly and its solved. just the guy concern got a server since a while now and know how to perform this kind of stuff. idk why he dont even reply here. 

the issue isnt persisting. he told me it was...

im not gonna report for him next time. if he dont want to do it its not my probleme.

**Comment by dryter97** [comment]
i want to let you know im sorry for the time it took.
