### ISSUE TITLE
[LICENSE] No, disallowing redistribution with a fee *probably* isn't allowed by the GPL

### ISSUE THREAD

**Issue by JacksonChen666** [PotatoCraft-Studio/QuickShop-Reremake#76]
This is an issue about and within the plugin page, probably an oversight. But the GPL license doesn't disallow the selling (or redistribution with a fee) of say, this plugin, or GPL licensed code.

([Here is a FAQ about selling GPL licensed software][gnu sell]. The next 3 sections might also answer questions)

Within the description of [this plugin][plugin], it says the following:
> We allow you to repost this plugin for free on other places as long as you follow these basic rules:
> - Keep a link to the original resource (This one)
> - Don't remove the author's name or claim that you made it
> - Use our download link. You can use adf.ly or another legit pay-per-click site.
> - You're not allowed to re-post, if your goal is to earn money with it
> - No Re-selling of this plugin. It has to be free!
> 
> *Resource Overview designed by Andre601 ❤*

With point 1, I'd agree because the GPL license requires the source to be *accessible* if you're (re)distributing (and the page contains a source code link).
With point 2, that makes sense to do, but I have no idea with the GPL license.
With point 3, that's a bit restrictive of a requirement.
With point 4, I think i misunderstood that sentence.
With point 5, oh boy is someone *REALLY* getting into the weeds of *potential* license violations

Overall, this is just a concern and that the rules should be reviewed, but also **I'm not a lawyer** (and you should get one if you have legal questions) but rather just a guy with a concern.

[gnu sell]: https://www.gnu.org/licenses/gpl-faq.html#DoesTheGPLAllowMoney
[plugin]: https://www.spigotmc.org/resources/quickshop-reremake-1-18-ready-multi-currency.62575/

**Comment by Ghost-chu** [comment]
For point 4: QuickShop (Actually is QuickShop-Reremake) we disallow peoples to re-sell the official build copy.

But If you label it with other name like QuickShop-Foobar, the re-sell is acceptable because that mean we don't need offer support for it.

Our support is free, so we disallow others re-sell the our software.

For point 3, we hope peoples can receive the latest updates on SpigotMC, we can publish announcement, fixes, patches on SpigotMC.


-----

All in all: The additional restrictions mainly due to pressure from our support services.

We provide the best possible support within our means for free.  
At this moment, we even didn't accept donate.  
And that's why we make those decision: free support for free software.  
If somebody re-selling our software, they should change the brand at least to avoid consume our free support time.

So basiclly those additional restrictions only appiled for QuickShop-Reremake itself, not includes Sources Code.

**Comment by sandtechnology** [comment]
First, with Point 2, we actually should claim who is owned this plugin code or wrote this, and prevent someone pretending it is the original author, so is making sense.
And for point 3-5, yes we should change this, since we are taking about the **free-software**, **the word free there is freedom but not price**, and it should have the source code access as well, I have remove that rules and change point 1 and 2 for respecting GPL license, thanks for pointing this.


But As GPL license says: it's WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
We providing the free support just for the community, if someone breaking rules, we will also taking measure as well: claiming is free to download and free of charge.
